import type { Product, StyleVibe } from "../types/product"

export const styleVibes: StyleVibe[] = [
  { id: "all", name: "All", description: "All styles", color: "bg-gray-500" },
  { id: "clean-girl", name: "Clean Girl", description: "Minimalist & natural", color: "bg-green-500" },
  { id: "coquette", name: "Coquette", description: "Feminine & romantic", color: "bg-pink-500" },
  { id: "streetcore", name: "Streetcore", description: "Urban & edgy", color: "bg-orange-500" },
  { id: "y2k", name: "Y2K", description: "Futuristic & metallic", color: "bg-purple-500" },
  { id: "dark-academia", name: "Dark Academia", description: "Scholarly & vintage", color: "bg-amber-700" },
  { id: "cottagecore", name: "Cottagecore", description: "Rural & whimsical", color: "bg-emerald-600" },
  { id: "grunge", name: "Grunge", description: "Alternative & rebellious", color: "bg-gray-800" },
]

export const products: Product[] = [
  {
    id: 1,
    name: "Floral Summer Dress",
    price: 89.99,
    originalPrice: 120,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2025-05-28_13-42-32_UTC.jpg-UQNTI0hu7rOjDaJqOupHS5cIr9gcGB.jpeg",
    category: "dresses",
    subcategory: "midi",
    description: "Cotton blend floral dress perfect for summer occasions",
    inStock: true,
    rating: 4.8,
    reviews: 124,
    brand: "Summer Bloom",
    material: "Cotton blend",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink", "Blue", "White"],
    vibe: "coquette",
    isNew: true,
    isSale: true,
  },
  {
    id: 2,
    name: "Minimalist White Tee",
    price: 45,
    originalPrice: 55,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2025-05-28_13-40-09_UTC.jpg-GVtdKP12Azx0MX5M3HBJwfuE4xlumD.jpeg",
    category: "tops",
    subcategory: "t-shirts",
    description: "100% organic cotton essential white tee",
    inStock: true,
    rating: 4.9,
    reviews: 89,
    brand: "Essential",
    material: "100% Organic Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Gray"],
    vibe: "clean-girl",
    isBestseller: true,
  },
  {
    id: 3,
    name: "High-Waist Denim Jeans",
    price: 95,
    originalPrice: 110,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2025-05-31_14-01-37_UTC.jpg-UMTfUudxR4PF3EYUQdTjZyHoui43gM.jpeg",
    category: "bottoms",
    subcategory: "jeans",
    description: "Classic high-waist denim with perfect fit",
    inStock: true,
    rating: 4.7,
    reviews: 156,
    brand: "Denim Co",
    material: "98% Cotton, 2% Elastane",
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Blue", "Black", "Light Blue"],
    vibe: "clean-girl",
    isBestseller: true,
    isSale: true,
  },
  {
    id: 4,
    name: "Oversized Blazer",
    price: 150,
    originalPrice: 180,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2025-05-27_13-46-16_UTC.jpg-njXxWKLgV3G4CTB2xgYHqjAgK96I9R.jpeg",
    category: "outerwear",
    subcategory: "blazers",
    description: "Structured wool blend blazer for professional looks",
    inStock: true,
    rating: 4.6,
    reviews: 78,
    brand: "Academic",
    material: "Wool blend",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Beige"],
    vibe: "dark-academia",
    isNew: true,
  },
  {
    id: 5,
    name: "Cottagecore Midi Skirt",
    price: 75,
    originalPrice: 90,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2025-06-02_11-31-19_UTC.jpg-pBzI1KYKDu9WYZE5Q57tUjZs9Uwupt.jpeg",
    category: "bottoms",
    subcategory: "skirts",
    description: "Flowing cotton midi skirt with vintage charm",
    inStock: true,
    rating: 4.8,
    reviews: 92,
    brand: "Country Lane",
    material: "Cotton",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blue", "Green", "Cream"],
    vibe: "cottagecore",
    isSale: true,
  },
  {
    id: 6,
    name: "Streetwear Cargo Pants",
    price: 85,
    originalPrice: 100,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2025-05-27_13-46-16_UTC.jpg-njXxWKLgV3G4CTB2xgYHqjAgK96I9R.jpeg",
    category: "bottoms",
    subcategory: "pants",
    description: "Utility-inspired cargo pants with modern fit",
    inStock: true,
    rating: 4.5,
    reviews: 67,
    brand: "Urban Edge",
    material: "Cotton twill",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Khaki", "Black", "Olive"],
    vibe: "streetcore",
    isNew: true,
  },
]
